"""scaffold_project.py -- generate a minimal project skeleton.

Supports Flutter, React Native, Jetpack Compose, SwiftUI, .NET MAUI,
Kotlin Multiplatform, Capacitor, and Tauri Mobile. Generated files are
UTF-8 without BOM.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def _sanitize(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower() or "app"


def _class_name(name: str) -> str:
    return "".join(part.capitalize() for part in _sanitize(name).split("_"))


def _render(content: str, name: str) -> str:
    package = _sanitize(name)
    return (
        content.replace("{Name}", _class_name(name))
        .replace("{name}", package)
        .replace("{package}", f"com.example.{package}")
    )


FLUTTER = {
    "README.md": """# {Name}

Minimal Flutter app generated by mobile-app-dev.

```bash
flutter pub get
flutter run
flutter test
```
""",
    "pubspec.yaml": """name: {name}
description: A generated mobile-app-dev Flutter starter.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
""",
    "analysis_options.yaml": """include: package:flutter_lints/flutter.yaml
""",
    "lib/main.dart": """import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: {Name}App()));
}

class Counter extends Notifier<int> {
  @override
  int build() => 0;

  void increment() => state++;
}

final counterProvider = NotifierProvider<Counter, int>(Counter.new);

class {Name}App extends ConsumerWidget {
  const {Name}App({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final count = ref.watch(counterProvider);
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('{Name}')),
        body: Center(
          child: FilledButton(
            onPressed: () => ref.read(counterProvider.notifier).increment(),
            child: Text('Count: $count'),
          ),
        ),
      ),
    );
  }
}
""",
    "test/widget_test.dart": """import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:{name}/main.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('counter increments', (tester) async {
    await tester.pumpWidget(const ProviderScope(child: {Name}App()));
    expect(find.textContaining('Count: 0'), findsOneWidget);
    await tester.tap(find.byType(FilledButton));
    await tester.pump();
    expect(find.textContaining('Count: 1'), findsOneWidget);
  });
}
""",
    ".gitignore": """.dart_tool/
build/
.flutter-plugins
.flutter-plugins-dependencies
pubspec.lock
""",
}


REACT_NATIVE = {
    "README.md": """# {Name}

Minimal React Native app generated by mobile-app-dev.

```bash
npm install
npm test
npx react-native run-android
npx react-native run-ios
```
""",
    "package.json": """{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.3.1",
    "react-native": "0.76.0",
    "zustand": "^5.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.25.0",
    "@babel/preset-env": "^7.25.0",
    "@babel/runtime": "^7.25.0",
    "@react-native/babel-preset": "0.76.0",
    "@react-native/eslint-config": "0.76.0",
    "@react-native/typescript-config": "0.76.0",
    "@testing-library/react-native": "^12.0.0",
    "@testing-library/jest-native": "^5.4.3",
    "@types/react": "^18.2.6",
    "babel-jest": "^29.0.0",
    "jest": "^29.0.0",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  }
}
""",
    "tsconfig.json": """{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "compilerOptions": {
    "strict": true
  }
}
""",
    "babel.config.js": """module.exports = {
  presets: ['module:@react-native/babel-preset'],
};
""",
    "jest.config.js": """module.exports = {
  preset: 'react-native',
  setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect'],
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|react-native-.*)/)',
  ],
};
""",
    "App.tsx": """import React from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';
import { create } from 'zustand';

type CounterState = {
  count: number;
  increment: () => void;
};

export const useCounterStore = create<CounterState>((set) => ({
  count: 0,
  increment: () => set((s) => ({ count: s.count + 1 })),
}));

export default function App() {
  const count = useCounterStore((s) => s.count);
  const increment = useCounterStore((s) => s.increment);
  return (
    <View style={styles.root}>
      <Text style={styles.title}>{count}</Text>
      <Button title="Increment" onPress={increment} />
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 48, fontWeight: '700' },
});
""",
    "App.test.tsx": """import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import App from './App';

test('increments counter', () => {
  const { getByText } = render(<App />);
  fireEvent.press(getByText('Increment'));
  expect(getByText('1')).toBeTruthy();
});
""",
    ".gitignore": """node_modules/
build/
ios/Pods/
android/.gradle/
*.log
""",
}


COMPOSE = {
    "README.md": """# {Name}

Minimal Jetpack Compose app generated by mobile-app-dev.

```bash
./gradlew :app:assembleDebug
adb install -r app/build/outputs/apk/debug/app-debug.apk
```
""",
    "settings.gradle.kts": """pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "{Name}"
include(":app")
""",
    "build.gradle.kts": """plugins {
    id("com.android.application") version "8.5.0" apply false
    id("org.jetbrains.kotlin.android") version "2.0.21" apply false
    id("org.jetbrains.kotlin.plugin.compose") version "2.0.21" apply false
}
""",
    "gradle.properties": """org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
""",
    "app/build.gradle.kts": """plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace = "{package}"
    compileSdk = 34

    defaultConfig {
        applicationId = "{package}"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "0.1.0"
    }
    buildFeatures {
        compose = true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.09.03")
    implementation(composeBom)
    implementation("androidx.activity:activity-compose:1.9.2")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui")
}
""",
    "app/src/main/AndroidManifest.xml": """<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="@string/app_name"
        android:theme="@android:style/Theme.Material.Light.NoActionBar">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
""",
    "app/src/main/java/{package}/MainActivity.kt": """package {package}

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                var count by remember { mutableIntStateOf(0) }
                Button(onClick = { count++ }) {
                    Text("Count: $count")
                }
            }
        }
    }
}
""",
    "app/src/main/res/values/strings.xml": """<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">{Name}</string>
</resources>
""",
    ".gitignore": """.gradle/
build/
local.properties
*.apk
*.aab
""",
}


SWIFTUI = {
    "README.md": """# {Name}

Minimal SwiftUI app generated by mobile-app-dev. Generate the Xcode
project with XcodeGen, or create a new Xcode iOS App project and add
the Sources/ files.

```bash
brew install xcodegen
xcodegen generate
open {Name}.xcodeproj
```
""",
    "project.yml": """name: {Name}
options:
  bundleIdPrefix: com.example
targets:
  {Name}:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: {package}
""",
    "Sources/{Name}App.swift": """import SwiftUI

@main
struct {Name}App: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
""",
    "Sources/ContentView.swift": """import SwiftUI

struct ContentView: View {
    @State private var count = 0

    var body: some View {
        Button("Count: \\(count)") {
            count += 1
        }
        .padding()
    }
}

#Preview {
    ContentView()
}
""",
    ".gitignore": """DerivedData/
build/
*.xcodeproj
""",
}


MAUI = {
    "README.md": """# {Name}

Minimal .NET MAUI app generated by mobile-app-dev.

```bash
dotnet restore
dotnet build -f net8.0-android
dotnet build -f net8.0-ios
```
""",
    "{Name}.csproj": """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-android;net8.0-ios</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>{Name}</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <MauiIcon Include="Resources/AppIcon/appicon.svg" />
    <MauiSplashScreen Include="Resources/Splash/splash.svg" />
  </ItemGroup>
</Project>
""",
    "MauiProgram.cs": """using Microsoft.Maui;
using Microsoft.Maui.Hosting;

namespace {Name};

public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder.UseMauiApp<App>();
        return builder.Build();
    }
}
""",
    "App.xaml": """<?xml version="1.0" encoding="UTF-8" ?>
<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="{Name}.App">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Resources/Styles/Colors.xaml" />
                <ResourceDictionary Source="Resources/Styles/Styles.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
""",
    "App.xaml.cs": """namespace {Name};

public partial class App : Application
{
    public App()
    {
        InitializeComponent();
        MainPage = new AppShell();
    }
}
""",
    "AppShell.xaml": """<?xml version="1.0" encoding="UTF-8" ?>
<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       x:Class="{Name}.AppShell">
    <ShellContent Title="Home" ContentTemplate="{DataTemplate local:MainPage}" />
</Shell>
""",
    "AppShell.xaml.cs": """namespace {Name};

public partial class AppShell : Shell
{
    public AppShell()
    {
        InitializeComponent();
    }
}
""",
    "MainPage.xaml": """<?xml version="1.0" encoding="UTF-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="{Name}.MainPage">
    <VerticalStackLayout Padding="24" Spacing="12">
        <Label x:Name="CountLabel" Text="Count: 0" FontSize="32" />
        <Button Text="Increment" Clicked="OnIncrementClicked" />
    </VerticalStackLayout>
</ContentPage>
""",
    "MainPage.xaml.cs": """namespace {Name};

public partial class MainPage : ContentPage
{
    private int _count;

    public MainPage()
    {
        InitializeComponent();
    }

    private void OnIncrementClicked(object sender, EventArgs e)
    {
        _count++;
        CountLabel.Text = $"Count: {_count}";
    }
}
""",
    "Resources/AppIcon/appicon.svg": """<svg width="1024" height="1024" xmlns="http://www.w3.org/2000/svg">
  <rect width="1024" height="1024" fill="#3B82F6"/>
  <text x="512" y="560" font-size="240" text-anchor="middle" fill="#fff">{Name}</text>
</svg>
""",
    "Resources/Splash/splash.svg": """<svg width="1024" height="1024" xmlns="http://www.w3.org/2000/svg">
  <rect width="1024" height="1024" fill="#ffffff"/>
</svg>
""",
    "Resources/Styles/Colors.xaml": """<?xml version="1.0" encoding="UTF-8" ?>
<ResourceDictionary xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <Color x:Key="Primary">#3B82F6</Color>
</ResourceDictionary>
""",
    "Resources/Styles/Styles.xaml": """<?xml version="1.0" encoding="UTF-8" ?>
<ResourceDictionary xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
</ResourceDictionary>
""",
    "Platforms/Android/AndroidManifest.xml": """<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application android:label="{Name}" />
</manifest>
""",
    "Platforms/iOS/Info.plist": """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDisplayName</key>
    <string>{Name}</string>
</dict>
</plist>
""",
    ".gitignore": """bin/
obj/
*.user
""",
}


KMP = {
    "README.md": """# {Name}

Minimal Kotlin Multiplatform starter generated by mobile-app-dev.
Create the Xcode app with XcodeGen, then build the shared framework:

```bash
./gradlew :shared:assembleXCFramework
```
""",
    "settings.gradle.kts": """pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "{Name}"
include(":shared")
include(":androidApp")
""",
"build.gradle.kts": """plugins {
    id("org.jetbrains.kotlin.multiplatform") version "2.0.21" apply false
    id("org.jetbrains.kotlin.android") version "2.0.21" apply false
    id("com.android.application") version "8.5.0" apply false
    id("com.android.library") version "8.5.0" apply false
}
""",
    "shared/build.gradle.kts": """plugins {
    kotlin("multiplatform")
    id("com.android.library")
}

kotlin {
    androidTarget()
    iosX64()
    iosArm64()
    iosSimulatorArm64()
    sourceSets {
        commonMain.dependencies {
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")
        }
    }
}

android {
    namespace = "{package}.shared"
    compileSdk = 34
}
""",
    "shared/src/commonMain/kotlin/{package}/Greeting.kt": """package {package}.shared

fun greeting(): String = "Hello from {Name}"
""",
    "androidApp/build.gradle.kts": """plugins {
    id("com.android.application")
    kotlin("android")
}

android {
    namespace = "{package}.android"
    compileSdk = 34
    defaultConfig {
        applicationId = "{package}.android"
        minSdk = 26
        targetSdk = 34
    }
}

dependencies {
    implementation(project(":shared"))
    implementation("androidx.appcompat:appcompat:1.7.0")
}
""",
    "androidApp/src/main/AndroidManifest.xml": """<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application android:label="{Name}">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
""",
    "androidApp/src/main/java/{package}/MainActivity.kt": """package {package}.android

import android.app.Activity
import android.os.Bundle
import {package}.shared.greeting

class MainActivity : Activity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        title = greeting()
    }
}
""",
    "iosApp/project.yml": """name: {Name}
options:
  bundleIdPrefix: com.example
targets:
  {Name}:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources]
    dependencies:
      - framework: ../shared/build/XCFrameworks/release/shared.xcframework
        embed: true
""",
    "iosApp/Sources/ContentView.swift": """import SwiftUI
import shared

struct ContentView: View {
    var body: some View {
        Text(greeting())
    }
}
""",
    ".gitignore": """.gradle/
build/
DerivedData/
*.xcodeproj
""",
}


CAPACITOR = {
    "README.md": """# {Name}

Minimal Capacitor app generated by mobile-app-dev.

```bash
npm install
npx cap sync
npx cap open ios
npx cap open android
```
""",
    "package.json": """{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "sync": "cap sync"
  },
  "dependencies": {
    "@capacitor/android": "^6.0.0",
    "@capacitor/core": "^6.0.0",
    "@capacitor/ios": "^6.0.0"
  },
  "devDependencies": {
    "@capacitor/cli": "^6.0.0"
  }
}
""",
    "capacitor.config.json": """{
  "appId": "{package}",
  "appName": "{Name}",
  "webDir": "www"
}
""",
    "www/index.html": """<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{Name}</title>
  </head>
  <body>
    <button id="button">Count: 0</button>
    <script>
      let count = 0;
      document.getElementById('button').addEventListener('click', () => {
        count++;
        document.getElementById('button').textContent = 'Count: ' + count;
      });
    </script>
  </body>
</html>
""",
    ".gitignore": """node_modules/
ios/
android/
""",
}


TAURI = {
    "README.md": """# {Name}

Minimal Tauri Mobile app generated by mobile-app-dev.

```bash
npm install
npm run tauri android init
npm run tauri android build
```
""",
    "package.json": """{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "tauri": "tauri"
  },
  "devDependencies": {
    "@tauri-apps/cli": "^2.0.0"
  }
}
""",
    "src/index.html": """<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{Name}</title>
  </head>
  <body>
    <button id="button">Count: 0</button>
    <script src="main.js"></script>
  </body>
</html>
""",
    "src/main.js": """let count = 0;
document.getElementById('button').addEventListener('click', () => {
  count++;
  document.getElementById('button').textContent = 'Count: ' + count;
});
""",
    "src-tauri/Cargo.toml": """[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[lib]
name = "{name}_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
""",
    "src-tauri/build.rs": """fn main() {
    tauri_build::build()
}
""",
    "src-tauri/tauri.conf.json": """{
  "$schema": "https://schema.tauri.app/config/2",
  "productName": "{Name}",
  "version": "0.1.0",
  "identifier": "{package}",
  "build": {
    "frontendDist": "../src"
  },
  "app": {
    "windows": [
      {
        "title": "{Name}",
        "width": 800,
        "height": 600
      }
    ]
  }
}
""",
    "src-tauri/src/main.rs": """fn main() {
    tauri::Builder::default()
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
""",
    ".gitignore": """node_modules/
src-tauri/target/
src-tauri/gen/
""",
}


SCAFFOLDS = {
    "flutter": FLUTTER,
    "react-native": REACT_NATIVE,
    "compose": COMPOSE,
    "swiftui": SWIFTUI,
    "maui": MAUI,
    "kmp": KMP,
    "capacitor": CAPACITOR,
    "tauri": TAURI,
}


def scaffold(framework: str, output_dir: Path, name: str) -> Path:
    key = framework.strip().lower()
    if key not in SCAFFOLDS:
        raise ValueError(f"Unsupported framework: {framework}")
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    for rel, content in SCAFFOLDS[key].items():
        package_path = f"com/example/{_sanitize(name)}"
        target = root / (
            rel.replace("{Name}", _class_name(name))
            .replace("{name}", _sanitize(name))
            .replace("{package}", package_path)
        )
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(_render(content, name).encode("utf-8"))
    return root


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a mobile project skeleton.")
    parser.add_argument("--framework", required=True, choices=sorted(SCAFFOLDS))
    parser.add_argument("--name", required=True, help="project/app name")
    parser.add_argument("--output-dir", default=".", help="output directory")
    args = parser.parse_args(argv)
    root = scaffold(args.framework, Path(args.output_dir), args.name)
    print(f"Scaffolded {args.framework} project in {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
